on:
  pull_request:

jobs:
  dismiss:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.base_ref, 'graphite-base/') }}
    steps:
      - uses: ryancalhoun-brt/dismiss-stale-approvals@main
        with:
          github-token: ${{ github.token }}
          dry-run: true
      - name: Github Context
        run: |
          echo "${{ toJSON(github) }}"
        shell: bash
      - name: PullRequest Context
        run: |
          echo "${{ toJSON(github.event.pull_request) }}"
        shell: bash
