on:
  pull_request:
    branches:
      - '!graphite-base/**'

jobs:
  dismiss:
    runs-on: ubuntu-latest
    steps:
      - uses: ryancalhoun-brt/dismiss-stale-approvals@main
        with:
          github-token: ${{ github.token }}
          dry-run: true
      - name: Github Context
        run: |
          echo "${{ toJSON(github) }}"
        shell: bash
      - name: PullRequest Context
        run: |
          echo "${{ toJSON(github.event.pull_request) }}"
        shell: bash
