on:
  pull_request:

jobs:
  dismiss:
    runs-on: ubuntu-latest
    steps:
      - uses: ryancalhoun-brt/dismiss-stale-approvals
        with:
          github-token: ${{ github.token }}
          dry-run: true
